/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CtxConsumer {
    'mapper': (val: any) => string;
    'name': string;
  }
  interface CtxGreetComp {}
  interface CtxProvider {
    'name': string;
    'value': any;
  }
  interface CtxTestComp {}
}

declare global {


  interface HTMLCtxConsumerElement extends Components.CtxConsumer, HTMLStencilElement {}
  var HTMLCtxConsumerElement: {
    prototype: HTMLCtxConsumerElement;
    new (): HTMLCtxConsumerElement;
  };

  interface HTMLCtxGreetCompElement extends Components.CtxGreetComp, HTMLStencilElement {}
  var HTMLCtxGreetCompElement: {
    prototype: HTMLCtxGreetCompElement;
    new (): HTMLCtxGreetCompElement;
  };

  interface HTMLCtxProviderElement extends Components.CtxProvider, HTMLStencilElement {}
  var HTMLCtxProviderElement: {
    prototype: HTMLCtxProviderElement;
    new (): HTMLCtxProviderElement;
  };

  interface HTMLCtxTestCompElement extends Components.CtxTestComp, HTMLStencilElement {}
  var HTMLCtxTestCompElement: {
    prototype: HTMLCtxTestCompElement;
    new (): HTMLCtxTestCompElement;
  };
  interface HTMLElementTagNameMap {
    'ctx-consumer': HTMLCtxConsumerElement;
    'ctx-greet-comp': HTMLCtxGreetCompElement;
    'ctx-provider': HTMLCtxProviderElement;
    'ctx-test-comp': HTMLCtxTestCompElement;
  }
}

declare namespace LocalJSX {
  interface CtxConsumer {
    'mapper'?: (val: any) => string;
    'name': string;
  }
  interface CtxGreetComp {}
  interface CtxProvider {
    'name': string;
    'value'?: any;
  }
  interface CtxTestComp {}

  interface IntrinsicElements {
    'ctx-consumer': CtxConsumer;
    'ctx-greet-comp': CtxGreetComp;
    'ctx-provider': CtxProvider;
    'ctx-test-comp': CtxTestComp;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'ctx-consumer': LocalJSX.CtxConsumer & JSXBase.HTMLAttributes<HTMLCtxConsumerElement>;
      'ctx-greet-comp': LocalJSX.CtxGreetComp & JSXBase.HTMLAttributes<HTMLCtxGreetCompElement>;
      'ctx-provider': LocalJSX.CtxProvider & JSXBase.HTMLAttributes<HTMLCtxProviderElement>;
      'ctx-test-comp': LocalJSX.CtxTestComp & JSXBase.HTMLAttributes<HTMLCtxTestCompElement>;
    }
  }
}


