/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {}
  interface TestComp {}
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLTestCompElement extends Components.TestComp, HTMLStencilElement {}
  var HTMLTestCompElement: {
    prototype: HTMLTestCompElement;
    new (): HTMLTestCompElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'test-comp': HTMLTestCompElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {}
  interface TestComp {}

  interface IntrinsicElements {
    'my-component': MyComponent;
    'test-comp': TestComp;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'test-comp': LocalJSX.TestComp & JSXBase.HTMLAttributes<HTMLTestCompElement>;
    }
  }
}


